// <auto-generated />
namespace Summer.Migrations.DataContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Student_attendance_cascade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Student_attendance_cascade));
        
        string IMigrationMetadata.Id
        {
            get { return "201907091758247_Student_attendance_cascade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
