// <auto-generated />
namespace Summer.Migrations.DataContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_time_attendance : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_time_attendance));
        
        string IMigrationMetadata.Id
        {
            get { return "201907091649425_Add_time_attendance"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
